/* Pixel Arcade 9.4 — compte persistant + profil connecté. */
(()=>{
  const cfg=window.PIXEL_ARCADE_CONFIG||{};
  const URL=String(cfg.supabaseUrl||'').replace(/\/$/,''),KEY=cfg.supabaseAnonKey||'';
  const EDGE=URL+'/functions/v1/pixel-login';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pseudoOk=/^[A-Za-z0-9À-ÿ _-]{3,20}$/;
  const emailOk=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  const state=()=>window.PAAuth?.state;
  const pseudo=()=>{const s=state();return window.PAAuth?.currentPseudo?.()||s?.profile?.pseudo||s?.user?.user?.user_metadata?.pseudo||''};
  const api=async(path,opt={})=>{const s=state();const token=opt.token||s?.user?.access_token||KEY;const r=await fetch(URL+path,{...opt,headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':'application/json',...(opt.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw Error(d?.msg||d?.message||d?.error_description||t||'Erreur');return d};
  async function realSignup(email,p,pw){email=email.trim();p=p.trim();if(!emailOk.test(email))throw Error('Entre une adresse e-mail valide.');if(!pseudoOk.test(p))throw Error('Pseudo : 3 à 20 caractères (lettres, chiffres, espaces, _ ou -).');if(pw.length<8)throw Error('Le mot de passe doit contenir au moins 8 caractères.');const d=await api('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password:pw,data:{pseudo:p}})});if(d?.access_token){const s=state();s.user={access_token:d.access_token,refresh_token:d.refresh_token,user:d.user};s.online=true;await window.PAAuth.refresh();return {logged:true,pseudo:p}}return {logged:false,pseudo:p,message:'Compte créé ! Vérifie ton e-mail pour confirmer ton compte, puis connecte-toi.'};}
  async function realLogin(id,pw){id=id.trim();if(!id||!pw)throw Error('Renseigne ton identifiant et ton mot de passe.');let d;if(id.includes('@'))d=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:id,password:pw})});else{const r=await fetch(EDGE,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({pseudo:id,password:pw})});const t=await r.text();let x=null;try{x=t?JSON.parse(t):null}catch{}if(!r.ok)throw Error(x?.message||'Connexion impossible. Vérifie ton pseudo et ton mot de passe.');d=x}if(!d?.access_token)throw Error('Connexion impossible. Vérifie tes identifiants.');const s=state();s.user={access_token:d.access_token,refresh_token:d.refresh_token,user:d.user};s.online=true;await window.PAAuth.refresh();return {logged:true,pseudo:pseudo()||d.user?.user_metadata?.pseudo||id};}
  function renderAccount(){document.querySelectorAll('#accountBox').forEach(host=>{const p=pseudo();host.innerHTML=p?`<button class="account-chip" onclick="PAAuth.open()">👤 ${esc(p)}</button>`:'<button class="account-chip" onclick="PAAuth.open()">👤 Compte</button>'})}
  function modal(){if(document.getElementById('paAuthModal'))return;const m=document.createElement('div');m.id='paAuthModal';m.className='pa-modal';m.innerHTML='<div class="pa-auth-box"><button class="pa-close" aria-label="Fermer">×</button><div class="pa-tabs"><button data-tab="login" class="active">Se connecter</button><button data-tab="signup">Créer un compte</button></div><div id="paAuthForm"></div><p id="paAuthMsg" class="muted"></p></div>';document.body.appendChild(m);m.querySelector('.pa-close').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};m.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>form(b.dataset.tab));function form(tab){m.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));m.querySelector('#paAuthForm').innerHTML=tab==='signup'?`<h2>✨ Créer mon compte</h2><label>E-mail<input id="paEmail" type="email" autocomplete="email" placeholder="ton@email.com"></label><label>Pseudo<input id="paPseudo" maxlength="20" autocomplete="username" placeholder="Ex. PixelMaster"></label><label>Mot de passe<input id="paPass" type="password" minlength="8" autocomplete="new-password" placeholder="8 caractères minimum"></label><button id="paSubmit" class="primary">Créer le compte</button>`:`<h2>👋 Connexion</h2><label>E-mail ou pseudo<input id="paIdentifier" autocomplete="username" placeholder="ton@email.com ou PixelMaster"></label><label>Mot de passe<input id="paPass" type="password" autocomplete="current-password" placeholder="Ton mot de passe"></label><button id="paSubmit" class="primary">Se connecter</button>`;m.querySelector('#paSubmit').onclick=async()=>{const msg=m.querySelector('#paAuthMsg'),b=m.querySelector('#paSubmit');msg.textContent='';b.disabled=true;try{const r=tab==='signup'?await realSignup(m.querySelector('#paEmail').value,m.querySelector('#paPseudo').value,m.querySelector('#paPass').value):await realLogin(m.querySelector('#paIdentifier').value,m.querySelector('#paPass').value);msg.textContent='✓ '+(r.message||((r.pseudo||'Compte')+' connecté !'));renderAccount();window.dispatchEvent(new Event('pa-auth-updated'));if(r.logged)setTimeout(()=>m.remove(),500)}catch(e){msg.textContent='⚠️ '+e.message}finally{b.disabled=false}}}form('login')}
  if(window.PAAuth){window.PAAuth.open=()=>{if(state()?.user)location.href='./profile.html';else modal()};window.PAAuth.emailSignup=realSignup;window.PAAuth.emailLogin=realLogin;}
  function renderProfile(){const root=document.getElementById('profilePage');if(!root)return;const s=state(),p=s?.profile||{},name=pseudo();if(!s?.user){root.innerHTML='<section class="panel center"><h2>👤 Mon profil</h2><p class="muted">Aucune session active sur cet appareil.</p><button class="primary" onclick="PAAuth.open()">Se connecter</button></section>';return}const xp=Number(p.xp)||0,level=1+Math.floor(xp/1000),games=Number(p.games_played)||0,total=Number(p.total_score)||0,favs=window.PAAuth.favoriteGames?.()||[],ach=window.PAAuth.achievements?.()||[],unlocked=new Set(Array.isArray(p.achievements)?p.achievements:[]);root.innerHTML=`<section class="profile-hero panel"><div class="avatar">${esc((name||'J').slice(0,1).toUpperCase())}</div><div class="profile-title"><span class="tag">COMPTE CONNECTÉ</span><h2>${esc(name||'Joueur')}</h2><p class="muted">Niveau ${level} · ${xp} XP</p></div><button class="back" id="logoutBtn">Se déconnecter</button></section><section class="profile-grid"><div class="panel"><h2>📊 Mes statistiques</h2><div class="stats profile-stats"><div class="stat"><b>${games}</b><span>parties</span></div><div class="stat"><b>${total}</b><span>score cumulé</span></div><div class="stat"><b>${favs.length}</b><span>favoris</span></div></div><div class="xpbar"><div style="width:${Math.min(100,xp%1000/10)}%"></div></div><p class="muted">${xp%1000}/1000 XP vers le niveau ${level+1}</p></div><div class="panel"><h2>🏅 Mes succès</h2>${ach.map(a=>`<div class="achievement ${unlocked.has(a.id)?'on':''}">${a.icon} <b>${esc(a.name)}</b><br><small>${esc(a.desc)} · ${unlocked.has(a.id)?'Débloqué':'À débloquer'}</small></div>`).join('')}</div></section><section class="panel"><h2>⭐ Mes favoris</h2><p class="muted">${favs.length?favs.map(esc).join(' · '):'Aucun favori pour le moment. Ajoute des jeux depuis l’arcade.'}</p></section><section class="panel profile-actions"><h2>🎮 Continuer à jouer</h2><a class="primary" href="./index.html">Retourner à l’arcade</a></section>`;document.getElementById('logoutBtn').onclick=async()=>{await window.PAAuth.logout();location.href='./index.html'};}
  if(window.PAAuth){window.PAAuth.renderProfilePage=async()=>{const s=state();if(!s?.user&&window.PAAuth.refresh)await window.PAAuth.refresh();renderProfile();window.dispatchEvent(new Event('pa-profile-rendered'));};}
  window.addEventListener('pa-auth-ready',()=>{renderAccount();if(location.pathname.endsWith('/profile.html')||location.pathname.endsWith('/profil.html'))renderProfile()});window.addEventListener('pa-auth-updated',()=>{renderAccount();if(document.getElementById('profilePage'))renderProfile()});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderAccount);else setTimeout(renderAccount,0);
  /* auth.js peut avoir lancé son boot avant que ce fichier soit chargé. On relance donc explicitement le profil ici. */
  if(document.getElementById('profilePage')&&window.PAAuth){setTimeout(async()=>{try{await window.PAAuth.renderProfilePage()}catch(e){console.warn('Profil:',e)}},50)}
})();