/* Pixel Arcade v9.0 — comptes, profils, favoris, succès et synchronisation. */
(()=>{
  const cfg=window.PIXEL_ARCADE_CONFIG||{};
  const URL=String(cfg.supabaseUrl||'').replace(/\/$/,''), KEY=cfg.supabaseAnonKey||'';
  const SESSION_KEY='pixelArcadeSession';
  const PROFILE_KEY='pixelArcadeProfile';
  const pseudoOk=/^[A-Za-z0-9À-ÿ _-]{3,20}$/;
  let state={user:null,profile:null,online:navigator.onLine};
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api=async(path,opt={})=>{if(!URL||!KEY)throw Error('Supabase non configuré');const token=opt.token||state.user?.access_token||KEY;const headers={'apikey':KEY,'Authorization':'Bearer '+token,'Content-Type':'application/json',...(opt.headers||{})};const r=await fetch(URL+path,{...opt,headers});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{}if(!r.ok)throw Error(data?.msg||data?.message||data?.error_description||text||r.statusText);return data};
  const emailFor=p=>p.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,20)+'@pixelarcade.local';
  function cache(){try{localStorage.setItem(SESSION_KEY,JSON.stringify(state.user||null));localStorage.setItem(PROFILE_KEY,JSON.stringify(state.profile||null))}catch{}}
  function readCache(){try{state.user=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');state.profile=JSON.parse(localStorage.getItem(PROFILE_KEY)||'null')}catch{}}
  async function loadProfile(){if(!state.user?.user?.id)return null;try{const d=await api('/rest/v1/profiles?id=eq.'+encodeURIComponent(state.user.user.id)+'&select=*');state.profile=d?.[0]||null;cache();return state.profile}catch{return state.profile}}
  async function refresh(){
    readCache();
    if(!URL||!KEY){render();return false}
    if(!state.user?.access_token){render();return false}
    try{const u=await api('/auth/v1/user');state.user.user=u;state.online=true;await loadProfile();cache();}
    catch(e){
      if(!navigator.onLine)return false;
      try{const r=await fetch(URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{'apikey':KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:state.user.refresh_token})});const d=await r.json();if(!r.ok||!d.access_token)throw Error('refresh');state.user={access_token:d.access_token,refresh_token:d.refresh_token,user:d.user};state.online=true;await loadProfile();cache();}
      catch{state.user=null;state.profile=null;cache()}
    }
    render();return !!state.user;
  }
  async function signup(pseudo,password){pseudo=pseudo.trim();if(!pseudoOk.test(pseudo))throw Error('Pseudo : 3 à 20 caractères (lettres, chiffres, espaces, _ ou -).');if(String(password).length<8)throw Error('Le mot de passe doit contenir au moins 8 caractères.');const d=await api('/auth/v1/signup',{method:'POST',body:JSON.stringify({email:emailFor(pseudo),password,data:{pseudo}})});if(!d?.access_token)throw Error('Le compte a été créé mais Supabase demande une confirmation e-mail. Dans Supabase, désactive la confirmation e-mail pour utiliser le mode pseudo + mot de passe.');state.user={access_token:d.access_token,refresh_token:d.refresh_token,user:d.user};state.online=true;await loadProfile();cache();render();return state.profile;}
  async function login(pseudo,password){pseudo=pseudo.trim();if(!pseudoOk.test(pseudo))throw Error('Pseudo invalide.');const d=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:emailFor(pseudo),password})});state.user={access_token:d.access_token,refresh_token:d.refresh_token,user:d.user};state.online=true;await loadProfile();cache();render();return state.profile;}
  async function logout(){try{if(state.user?.access_token)await api('/auth/v1/logout',{method:'POST'})}catch{}state={user:null,profile:null,online:navigator.onLine};cache();render();}
  function currentPseudo(){return state.profile?.pseudo||state.user?.user?.user_metadata?.pseudo||''}
  function isOnline(){return navigator.onLine&&!!URL&&!!KEY&&!!state.user?.access_token}
  async function recordScore(game,score,players=1,pseudo='Joueur'){const now=new Date().toISOString();let saved=false;const p=currentPseudo()||pseudo||'Joueur';try{if(isOnline()){await api('/rest/v1/scores',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({game,score:Math.round(score),players,pseudo:p,user_id:state.user.user.id})});saved=true;if(state.profile){const total=(Number(state.profile.total_score)||0)+Math.round(score);const games=(Number(state.profile.games_played)||0)+1;const xp=(Number(state.profile.xp)||0)+Math.max(10,Math.floor(score/10));const ach=new Set(Array.isArray(state.profile.achievements)?state.profile.achievements:[]);if(games>=1)ach.add('first_game');if(games>=10)ach.add('ten_games');if(total>=10000)ach.add('score_10000');if(score>=1000)ach.add('score_1000');const patch={total_score:total,games_played:games,xp,achievements:[...ach]};try{await api('/rest/v1/profiles?id=eq.'+encodeURIComponent(state.user.user.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(patch)});Object.assign(state.profile,patch);cache()}catch{}}}}catch(e){console.warn('Synchronisation score:',e)}try{const a=JSON.parse(localStorage.getItem('pixelArcadeScores')||'[]');a.unshift({game,score:Math.round(score),players,pseudo:p,user_id:state.user?.user?.id||null,created_at:now,synced:saved});localStorage.setItem('pixelArcadeScores',JSON.stringify(a.slice(0,100)))}catch{}return saved;}
  async function saveAnonymousScore(game,score,players,pseudo){const p=(pseudo||'Joueur').trim().replace(/[^a-zA-Z0-9À-ÿ _-]/g,'').slice(0,20)||'Joueur';let online=false;try{if(navigator.onLine&&URL&&KEY){await api('/rest/v1/scores',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({game,score:Math.round(score),players,pseudo:p})});online=true}}catch(e){console.warn('Score anonyme:',e)}try{const a=JSON.parse(localStorage.getItem('pixelArcadeScores')||'[]');a.unshift({game,score:Math.round(score),players,pseudo:p,created_at:new Date().toISOString(),synced:online});localStorage.setItem('pixelArcadeScores',JSON.stringify(a.slice(0,100)));localStorage.setItem('pixelArcadePseudo',p)}catch{}return online;}
  async function syncPendingScores(){if(!navigator.onLine||!URL||!KEY)return 0;let a=[];try{a=JSON.parse(localStorage.getItem('pixelArcadeScores')||'[]')}catch{return 0}let count=0,changed=false;for(const r of a){if(r.synced)continue;if(r.user_id&&r.user_id!==state.user?.user?.id)continue;try{const body={game:r.game,score:Number(r.score)||0,players:Number(r.players)||1,pseudo:r.pseudo||currentPseudo()||'Joueur'};if(state.user?.user?.id)body.user_id=state.user.user.id;await api('/rest/v1/scores',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});r.synced=true;changed=true;count++}catch{}}if(changed)try{localStorage.setItem('pixelArcadeScores',JSON.stringify(a.slice(0,100)))}catch{}return count;}
  function profile(){return state.profile}
  function achievements(){return [{id:'first_game',name:'Première partie',desc:'Terminer une partie',icon:'🎮'},{id:'ten_games',name:'Habitué',desc:'Jouer 10 parties',icon:'🔥'},{id:'score_1000',name:'Mille points',desc:'Faire 1 000 points en une partie',icon:'💯'},{id:'score_10000',name:'Dix mille',desc:'Cumuler 10 000 points',icon:'🏆'}]}
  function localFavorites(){try{return JSON.parse(localStorage.getItem('pixelArcadeFavorites')||'[]')}catch{return []}}
  function favoriteGames(){return Array.isArray(state.profile?.favorites)?state.profile.favorites:localFavorites()}
  async function toggleFavorite(game){if(!state.user?.user?.id||!state.profile){const a=new Set(localFavorites());a.has(game)?a.delete(game):a.add(game);try{localStorage.setItem('pixelArcadeFavorites',JSON.stringify([...a]))}catch{};render();return true;}const a=new Set(favoriteGames());a.has(game)?a.delete(game):a.add(game);const favorites=[...a];try{await api('/rest/v1/profiles?id=eq.'+encodeURIComponent(state.user.user.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({favorites})});state.profile.favorites=favorites;cache();render();return true}catch{return false}}
  async function updateProfile(patch){if(!state.user?.user?.id)return false;await api('/rest/v1/profiles?id=eq.'+encodeURIComponent(state.user.user.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(patch)});Object.assign(state.profile,patch);cache();render();return true}
  async function globalLeaderboard(){try{const d=await api('/rest/v1/scores?select=pseudo,score,game&order=score.desc&limit=100');const best={};for(const r of (d||[])){const k=r.pseudo||'Joueur';if(!best[k]||Number(r.score)>Number(best[k].score))best[k]=r}return Object.values(best).sort((a,b)=>b.score-a.score).slice(0,10)}catch{return []}}
  async function renderGlobal(){const el=$('#globalScores');if(!el)return;const d=await globalLeaderboard();el.innerHTML=d.length?d.map((r,i)=>`<div class="row"><span>#${i+1} · ${esc(r.pseudo)} · ${esc(r.game||'')}</span><b>${Number(r.score)||0}</b></div>`).join(''):'<p class="muted">Configure Supabase pour activer le classement mondial.</p>'}
  function modal(){if($('#paAuthModal'))return;const m=document.createElement('div');m.id='paAuthModal';m.className='pa-modal';m.innerHTML='<div class="pa-auth-box"><button class="pa-close" aria-label="Fermer">×</button><div class="pa-tabs"><button data-tab="login" class="active">Se connecter</button><button data-tab="signup">Créer un compte</button></div><div id="paAuthForm"></div><p id="paAuthMsg" class="muted"></p></div>';document.body.appendChild(m);m.querySelector('.pa-close').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};m.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>form(b.dataset.tab));function form(tab){m.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));m.querySelector('#paAuthForm').innerHTML=`<h2>${tab==='login'?'👋 Connexion':'✨ Créer mon compte'}</h2><label>Pseudo<input id="paPseudo" maxlength="20" autocomplete="username" placeholder="Ex. PixelMaster"></label><label>Mot de passe<input id="paPass" type="password" minlength="8" autocomplete="${tab==='login'?'current-password':'new-password'}" placeholder="8 caractères minimum"></label><button id="paSubmit" class="primary">${tab==='login'?'Se connecter':'Créer le compte'}</button>`;m.querySelector('#paSubmit').onclick=async()=>{const msg=m.querySelector('#paAuthMsg');msg.textContent='';try{m.querySelector('#paSubmit').disabled=true;const p=tab==='login'?await login(m.querySelector('#paPseudo').value,m.querySelector('#paPass').value):await signup(m.querySelector('#paPseudo').value,m.querySelector('#paPass').value);msg.textContent='✓ '+(p?.pseudo||m.querySelector('#paPseudo').value)+' connecté !';setTimeout(()=>m.remove(),500)}catch(e){msg.textContent='⚠️ '+e.message}finally{m.querySelector('#paSubmit').disabled=false}}}form('login')}
  function open(){if(!state.user)modal();else window.location.href='profil.html'}
  function render(){document.querySelectorAll('[data-game-card]').forEach(card=>{if(card.dataset.paBound)return;card.dataset.paBound='1';const g=card.dataset.game;const b=document.createElement('button');b.className='favorite-btn';b.type='button';b.dataset.favoriteGame=g;b.textContent=(favoriteGames().includes(g)||localFavorites().includes(g))?'★ Favori':'☆ Favori';b.onclick=e=>{e.preventDefault();e.stopPropagation();toggleFavorite(g)};card.appendChild(b)});const host=$('#accountBox');if(host){if(state.user){const p=currentPseudo();host.innerHTML=`<button class="account-chip" onclick="PAAuth.open()">👤 ${esc(p)}</button>`}else host.innerHTML='<button class="account-chip" onclick="PAAuth.open()">👤 Compte</button>'}document.querySelectorAll('[data-favorite-game]').forEach(b=>{const g=b.dataset.favoriteGame;b.textContent=favoriteGames().includes(g)?'★ Favori':'☆ Favori'});renderGlobal();window.dispatchEvent(new Event('pa-auth-updated'));}
  async function renderProfilePage(){const root=$('#profilePage');if(!root)return;await refresh();const p=state.profile;if(!state.user||!p){root.innerHTML='<div class="panel center"><h2>👤 Mon profil</h2><p class="muted">Connecte-toi pour voir ton profil.</p><button class="primary" onclick="PAAuth.open()">Se connecter</button></div>';return}const ach=achievements(),unlocked=new Set(Array.isArray(p.achievements)?p.achievements:[]);root.innerHTML=`<section class="profile-hero panel"><div class="avatar">${esc((p.pseudo||'J').slice(0,1).toUpperCase())}</div><div><span class="tag">PROFIL JOUEUR</span><h2>${esc(p.pseudo)}</h2><p class="muted">Niveau ${1+Math.floor((Number(p.xp)||0)/1000)} · ${Number(p.xp)||0} XP</p></div><button class="back" id="logoutBtn">Se déconnecter</button></section><section class="profile-grid"><div class="panel"><h2>📊 Statistiques</h2><div class="stats profile-stats"><div class="stat"><b>${Number(p.games_played)||0}</b><span>parties</span></div><div class="stat"><b>${Number(p.total_score)||0}</b><span>score cumulé</span></div><div class="stat"><b>${favoriteGames().length}</b><span>favoris</span></div></div></div><div class="panel"><h2>🏅 Succès</h2>${ach.map(a=>`<div class="achievement ${unlocked.has(a.id)?'on':''}">${a.icon} <b>${esc(a.name)}</b><br><small>${esc(a.desc)} · ${unlocked.has(a.id)?'Débloqué':'À débloquer'}</small></div>`).join('')}</div></section><section class="panel"><h2>⭐ Mes favoris</h2><p class="muted">${favoriteGames().length?favoriteGames().map(esc).join(' · '):'Aucun favori pour le moment.'}</p></section>`;$('#logoutBtn').onclick=logout;}
  window.PAAuth={refresh,signup,login,logout,open,profile,currentPseudo,isOnline,recordScore,saveAnonymousScore,syncPendingScores,toggleFavorite,updateProfile,achievements,favoriteGames,globalLeaderboard,renderGlobal,renderProfilePage,get state(){return state}};
  window.addEventListener('online',async()=>{state.online=true;await refresh();await syncPendingScores();render()});window.addEventListener('offline',()=>{state.online=false;render()});
  async function boot(){render();await refresh();await syncPendingScores();render();window.dispatchEvent(new Event('pa-auth-ready'));}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
