/* Pixel Arcade 9.7 — profil : rendu unique, paramètres et scores. */
(()=>{
  const palettes={violet:['#8b5cf6','#c084fc'],blue:['#38bdf8','#60a5fa'],green:['#22c55e','#84cc16'],red:['#f43f5e','#fb7185'],orange:['#f97316','#facc15'],pink:['#ec4899','#f472b6']};
  const cfg=window.PIXEL_ARCADE_CONFIG||{};const URL=String(cfg.supabaseUrl||'').replace(/\/$/,''),KEY=cfg.supabaseAnonKey||'';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const state=()=>window.PAAuth?.state;
  function applyTheme(){const theme=localStorage.getItem('paTheme')||'dark';const palette=localStorage.getItem('paPalette')||'violet';document.documentElement.dataset.paTheme=theme;document.documentElement.dataset.paPalette=palette;const p=palettes[palette]||palettes.violet;document.documentElement.style.setProperty('--pa-accent',p[0]);document.documentElement.style.setProperty('--pa-accent-2',p[1]);}
  function api(path,opt={}){const s=state();return fetch(URL+path,{...opt,headers:{apikey:KEY,Authorization:'Bearer '+(s?.user?.access_token||KEY),'Content-Type':'application/json',...(opt.headers||{})}}).then(async r=>{const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw Error(d?.message||d?.msg||t||'Erreur');return d})}
  async function scores(){const id=state()?.user?.user?.id;if(!id)return [];try{return await api('/rest/v1/scores?user_id=eq.'+encodeURIComponent(id)+'&select=game,score,created_at,players&order=created_at.desc&limit=100')}catch{return []}}
  async function savePseudo(newPseudo){newPseudo=newPseudo.trim();if(!/^[A-Za-z0-9À-ÿ _-]{3,20}$/.test(newPseudo))throw Error('Pseudo : 3 à 20 caractères.');if(!state()?.profile)throw Error('Profil introuvable.');await window.PAAuth.updateProfile({pseudo:newPseudo});try{localStorage.setItem('pixelArcadeProfile',JSON.stringify(state().profile))}catch{}return newPseudo}
  function controls(){return `<section class="panel settings-panel"><h2>⚙️ Personnaliser mon compte</h2><div class="settings-grid"><div><label>Nouveau pseudo<input id="newPseudo" maxlength="20" value="${esc(window.PAAuth.currentPseudo()||'')}"></label><button class="primary" id="savePseudo">Enregistrer le pseudo</button><p id="pseudoMsg" class="muted"></p></div><div><label>Thème<select id="themeChoice"><option value="dark">🌙 Sombre</option><option value="light">☀️ Clair</option><option value="system">💻 Automatique</option></select></label><div class="palette-label">Couleur principale</div><div class="palette-choices" id="paletteChoices">${Object.keys(palettes).map(k=>`<button type="button" class="palette-choice" data-palette="${k}" title="${k}"><span class="theme-dot ${k}"></span><span>${k==='violet'?'Violet':k==='blue'?'Bleu':k==='green'?'Vert':k==='red'?'Rouge':k==='orange'?'Orange':'Rose'}</span></button>`).join('')}</div><button class="secondary" id="saveTheme">Appliquer le thème</button></div></div></section>`}
  async function render(){
    const root=document.getElementById('profilePage');if(!root||!window.PAAuth)return;const s=state();if(!s?.user)return;
    /* IMPORTANT : on reconstruit TOUT le profil au lieu d'ajouter des sections. Ainsi, même si render() est appelé 2, 3 ou 4 fois, il n'y aura jamais de doublon. */
    const scoresList=await scores();
    if(state()?.user?.user?.id!==s.user?.user?.id)return;
    const p=s.profile||{},name=window.PAAuth.currentPseudo()||'Joueur';
    const xp=Number(p.xp)||0,level=1+Math.floor(xp/1000),games=Number(p.games_played)||0,total=Number(p.total_score)||0;
    const favs=window.PAAuth.favoriteGames?.()||[],ach=window.PAAuth.achievements?.()||[],unlocked=new Set(Array.isArray(p.achievements)?p.achievements:[]);
    const names={memory:'Memory Grid',meteor:'Meteor Dodge',snake:'Snake',breakout:'Brick Breaker',clicker:'Mega Clicker',quiz:'Quiz Blitz',tetris:'Pixel Tetris',invaders:'Space Invaders',racer:'Pixel Racer',dungeon:'Mini Dungeon','2048':'2048',mines:'Mines',runner:'Pixel Runner',flappy:'Flappy Pixel',reaction:'Reaction Rush',aim:'Aim Trainer',whack:'Whack Pixel',color:'Color Match',typing:'Typing Blitz',number:'Number Rush',dot:'Dot Catch',simon:'Simon Pulse',pong:'Pong Duel',ttt:'Morpion',draw:'Quick Draw',tap:'Tap Battle',rps:'Shifumi',lights:'Light Race',dots:'Dot Duel',math:'Math Duel'};
    const best={};for(const r of scoresList){const g=r.game||'jeu';if(!best[g]||Number(r.score)>Number(best[g].score))best[g]=r}
    const bestRows=Object.entries(best).sort((a,b)=>Number(b[1].score)-Number(a[1].score));const history=scoresList.slice(0,20);
    root.innerHTML=`<section class="profile-hero panel"><div class="avatar">${esc((name||'J').slice(0,1).toUpperCase())}</div><div class="profile-title"><span class="tag">COMPTE CONNECTÉ</span><h2>${esc(name)}</h2><p class="muted">Niveau ${level} · ${xp} XP</p></div><button class="back" id="logoutBtn">Se déconnecter</button></section><section class="profile-grid"><div class="panel"><h2>📊 Mes statistiques</h2><div class="stats profile-stats"><div class="stat"><b>${games}</b><span>parties</span></div><div class="stat"><b>${total}</b><span>score cumulé</span></div><div class="stat"><b>${favs.length}</b><span>favoris</span></div></div><div class="xpbar"><div style="width:${Math.min(100,xp%1000/10)}%"></div></div><p class="muted">${xp%1000}/1000 XP vers le niveau ${level+1}</p></div><div class="panel"><h2>🏅 Mes succès</h2>${ach.map(a=>`<div class="achievement ${unlocked.has(a.id)?'on':''}">${a.icon} <b>${esc(a.name)}</b><br><small>${esc(a.desc)} · ${unlocked.has(a.id)?'Débloqué':'À débloquer'}</small></div>`).join('')}</div></section><section class="panel"><h2>⭐ Mes favoris</h2><p class="muted">${favs.length?favs.map(esc).join(' · '):'Aucun favori pour le moment. Ajoute des jeux depuis l’arcade.'}</p></section>${controls()}<section class="panel"><h2>🏆 Mes meilleurs scores</h2><p class="muted">Ton meilleur score pour chaque jeu où tu as joué.</p><div class="score-list">${bestRows.length?bestRows.map(([g,r],i)=>`<div class="score-row"><span><b>#${i+1}</b> ${esc(names[g]||g)}</span><strong>${Number(r.score)||0}</strong></div>`).join(''):'<p class="muted">Tu n’as pas encore enregistré de score.</p>'}</div></section><section class="panel"><h2>🕹️ Mes dernières parties</h2><div class="score-list">${history.length?history.map(r=>`<div class="score-row"><span>${esc(names[r.game]||r.game||'Jeu')} · ${r.created_at?new Date(r.created_at).toLocaleDateString('fr-FR'):''}</span><strong>${Number(r.score)||0}</strong></div>`).join(''):'<p class="muted">Aucune partie enregistrée.</p>'}</div></section><section class="panel profile-actions"><h2>🎮 Continuer à jouer</h2><a class="primary" href="./index.html">Retourner à l’arcade</a></section>`;
    const theme=localStorage.getItem('paTheme')||'dark',palette=localStorage.getItem('paPalette')||'violet';const themeEl=document.getElementById('themeChoice');if(themeEl)themeEl.value=theme;document.querySelectorAll('.palette-choice').forEach(b=>b.classList.toggle('selected',b.dataset.palette===palette));
    document.querySelectorAll('.palette-choice').forEach(b=>b.onclick=()=>{localStorage.setItem('paPalette',b.dataset.palette);applyTheme();document.querySelectorAll('.palette-choice').forEach(x=>x.classList.toggle('selected',x===b))});
    document.getElementById('saveTheme').onclick=()=>{localStorage.setItem('paTheme',document.getElementById('themeChoice').value);applyTheme()};
    document.getElementById('savePseudo').onclick=async()=>{const msg=document.getElementById('pseudoMsg'),b=document.getElementById('savePseudo');try{b.disabled=true;msg.textContent='';await savePseudo(document.getElementById('newPseudo').value);msg.textContent='✓ Pseudo modifié !';window.dispatchEvent(new Event('pa-auth-updated'))}catch(e){msg.textContent='⚠️ '+e.message}finally{b.disabled=false}};
    document.getElementById('logoutBtn').onclick=async()=>{await window.PAAuth.logout();location.href='./index.html'};
  }
  applyTheme();window.PAProfilePlus={render,applyTheme};window.addEventListener('pa-auth-ready',()=>setTimeout(render,50));window.addEventListener('pa-auth-updated',()=>{applyTheme();if(document.getElementById('profilePage'))setTimeout(render,80)});window.addEventListener('pa-profile-rendered',()=>{if(document.getElementById('profilePage'))setTimeout(render,20)});if(document.getElementById('profilePage'))setTimeout(render,300);
})();