/* Pixel Arcade v8 — couche de modernisation. */
(()=>{
  const CFG=window.PIXEL_ARCADE_CONFIG||{};
  const URL=CFG.supabaseUrl||"", KEY=CFG.supabaseAnonKey||"";
  const GAME_NAMES={runner:"Pixel Runner",memory:"Memory Grid",meteor:"Meteor Dodge",snake:"Snake",breakout:"Brick Breaker",flappy:"Flappy Pixel",reaction:"Reaction Rush",quiz:"Quiz Blitz",clicker:"Mega Clicker",pong:"Pong Duel",ttt:"Morpion",draw:"Quick Draw",tap:"Tap Battle",rps:"Shifumi",lights:"Light Race",dots:"Dot Duel",math:"Math Duel"};
  const $=id=>document.getElementById(id), game=()=>document.body.dataset.game||"";
  let online=false, current=null, finished=false;
  const local=()=>{try{return JSON.parse(localStorage.getItem("pixelArcadeScores")||"[]")}catch{return[]}};
  const saveLocal=(g,s,p,n)=>{let a=local();a.unshift({game:g,score:Math.round(s),players:p,pseudo:n,created_at:new Date().toISOString()});a=a.slice(0,100);try{localStorage.setItem("pixelArcadeScores",JSON.stringify(a));localStorage.setItem("pixelArcadePseudo",n)}catch{}};
  async function api(path,opt={}){if(!URL||!KEY)throw Error("Supabase non configuré");const r=await fetch(URL+"/rest/v1/"+path,{...opt,headers:{apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json",...(opt.headers||{})}});if(!r.ok)throw Error(await r.text()||r.statusText);const t=await r.text();return t?JSON.parse(t):null}
  async function load(){const el=$("scores");if(!el)return;const g=game();let d=[];try{d=online&&g?await api("scores?game=eq."+encodeURIComponent(g)+"&select=score,players,pseudo,created_at&order=score.desc&limit=10"):local().filter(x=>!g||x.game===g).sort((a,b)=>b.score-a.score).slice(0,10)}catch{d=local().filter(x=>!g||x.game===g).sort((a,b)=>b.score-a.score).slice(0,10)}el.innerHTML=d.length?d.map((x,i)=>`<div class="row"><span>#${i+1} · ${esc(x.pseudo||"Joueur")} · ${x.players||1}P</span><b>${x.score}</b></div>`).join(""):"<p class=muted>Aucun score pour ce jeu.</p>"}
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  async function init(){const c=$("connection"),dot=$("dot");try{if(!URL||!KEY)throw Error();await api("scores?select=id&limit=1");online=true;if(c)c.textContent="Scores en ligne : actif";if(dot)dot.style.background="var(--good)"}catch{if(c)c.textContent="Scores en ligne : non configuré";if(dot)dot.style.background="var(--muted)"}load()}
  async function finish(g,s,p=1){if(finished)return;finished=true;try{window.clearGame?.()}catch{}await exit();const pts=Math.max(0,Math.round(s));const area=$("game");if(!area)return;area.innerHTML=`<div class="finish"><div class="tag">PARTIE TERMINÉE</div><h2>${esc(GAME_NAMES[g]||g)}</h2><div class="big">${pts}</div><p class="muted">Score de la partie</p><input id="pseudoInput" class="pseudo" maxlength="20" autocomplete="nickname" placeholder="Ton pseudo"><button class="primary" id="saveScoreBtn">Enregistrer le score</button><p id="saveMsg" class="muted">Ton score sera enregistré ici et en ligne si la connexion est activée.</p></div>`;const inp=$("pseudoInput");inp.value=localStorage.getItem("pixelArcadePseudo")||"";inp.focus();$("saveScoreBtn").onclick=async()=>{let n=inp.value.trim().replace(/[^a-zA-Z0-9À-ÿ _-]/g,"");if(n.length<3)n="Joueur";saveLocal(g,pts,p,n);let ok=false;if(online)try{await api("scores",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({game:g,score:pts,players:p,pseudo:n})});ok=true}catch(e){console.warn(e)}$("saveMsg").textContent=ok?"✓ Score enregistré en ligne et sur cet appareil.":"✓ Score enregistré sur cet appareil.";$("saveScoreBtn").disabled=true;$("saveScoreBtn").textContent="Score enregistré";const b=document.createElement("button");b.className="back";b.textContent="↻ Rejouer";b.onclick=()=>start(g);$("saveScoreBtn").after(b);load()}}
  async function enter(){document.body.classList.add("playing");try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen()}catch{}setTimeout(()=>$("game")?.scrollIntoView({block:"center"}),80)}
  async function exit(){document.body.classList.remove("playing");try{if(document.fullscreenElement&&document.exitFullscreen)await document.exitFullscreen()}catch{}}
  function start(n){if(typeof window[n]!=="function"){const g=$("game");if(g)g.innerHTML='<div class="finish"><h2>Jeu introuvable</h2><p class="muted">Impossible de charger ce jeu.</p></div>';return}try{window.clearGame?.()}catch{}finished=false;current=n;enter();window[n]();}
  function launchGame(){start(game())}
  async function downloadGame(){const [css,js,patch,cfg]=await Promise.all([fetch("style.css").then(r=>r.text()),fetch("games.js").then(r=>r.text()),fetch("v8.js").then(r=>r.text()),fetch("config.js").then(r=>r.text())]);const clone=document.documentElement.cloneNode(true);clone.querySelectorAll("script[src],link[rel=stylesheet],link[rel=icon]").forEach(e=>e.remove());const st=document.createElement("style");st.textContent=css;clone.querySelector("head").appendChild(st);const s=document.createElement("script");s.textContent=cfg+"\n"+js+"\n"+patch;clone.body.appendChild(s);const blob=new Blob(["<!doctype html>\n",clone.outerHTML],{type:"text/html;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=(GAME_NAMES[game()]||"pixel-arcade").toLowerCase().replace(/[^a-z0-9]+/gi,"-")+".html";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  window.start=start;window.launchGame=launchGame;window.restartCurrent=()=>current&&start(current);window.score=finish;window.loadScores=load;window.downloadGame=downloadGame;window.home=()=>location.href="index.html";window.enterGameFullscreen=enter;window.exitGameFullscreen=exit;
  window.addEventListener("fullscreenchange",()=>{if(!document.fullscreenElement)document.body.classList.remove("playing")});
  window.addEventListener("DOMContentLoaded",()=>{const b=$("themeBtn");if(b)b.onclick=()=>{const light=!document.body.classList.contains("light");document.body.classList.toggle("light",light);localStorage.setItem("pixelArcadeTheme",light?"light":"dark")};const t=localStorage.getItem("pixelArcadeTheme");if(t==="light")document.body.classList.add("light");init()});
})();
